### ISSUE TITLE
More efficient

### ISSUE THREAD

**Issue by NitroVenom** [patzly/doodle-android#13]
Bro rewrite the app in kotlin, java slow.

**Comment by NitroVenom** [comment]
You could also write in C++

**Comment by patzly** [comment]
That's not a very helpful issue and please use at least whole sentences... I know that Kotlin is more efficient, but for example it makes the apk size larger, because it's only an additional library which also uses Java internally.

Also I have no problems with Java at all, so why should I rewrite it?
