### ISSUE TITLE
The options are not coming but just a white blank screen 

### ISSUE THREAD

**Issue by pantherzr7** [patzly/doodle-android#45]

**Comment by patzly** [comment]
You're not the first one reporting that (others via mail), thanks for opening the issue! The issue is known from other projects, but sadly nobody has a solution yet. My implementation of navigation component (a fragment navigation library) seems right, it's just the official way I used it.
Please give me more information, which Android version you have, your manufacturer and so on.

**Comment by patzly** [comment]
Doodle is currently running on 16000 devices and only a handful of users have this problem:
Android 9, Huawei (2 reports)
Android 9, Samsung (1 report)
Do you have similar specs like one of them?

What happens if you rotate your screen (turn on auto rotation) so that the app is in landscape mode and then back into portrait mode?

**Comment by patzly** [comment]
@pantherzr7 Does it still not work with the latest update?
