### ISSUE TITLE
Custom Wallpapers and more Wallpaper Options

### ISSUE THREAD

**Issue by DustinRoundy** [patzly/doodle-android#50]
Hello, 
First of all, I want to say I love your app so much! The wallpapers are just so amazing! Thank you for putting together this app and all of the wallpapers.

I'd love to see more wallpaper options or even custom wallpapers in the future. I'm not sure how you render each wallpapers and what goes in to making one of these wallpapers, but I'd definitely love to have more options!

Thanks again! Love all your hard work!

**Comment by patzly** [comment]
Thank you for your big compliments!
Please read the information section in the app by tapping on the info card on the start page. As the app depends on my own parallax rendering algorithm, it won't be possible to add custom wallpapers, because the existing wallpapers are internally stored as SVG files with special specifications. Users would have to extract every shape of a bitmap wallpaper as a seperate SVG object, like I have done with the Pixel wallpapers, but that is so much work for every single wallpaper option...
There are more options coming, specifically a grey and a yellow version of the Material You wallpapers from the Pixel 6 leak, as soon as I have enough time.

Thanks for your request!
