### ISSUE TITLE
Change the color of the wallpaper, depending on the activation of the dark mode

### ISSUE THREAD

**Issue by extropista** [patzly/doodle-android#63]
I saw this functionality in gnome (the latest version with Fedora), and it is interesting since it better integrates the images with the system.
I was looking for similar applications that do it, and I also found one called "Dark Mode Wallpaper". Here is the source code, it would be interesting to include something like that.

[github.com/.../darkmodewallpaper](https://github.com/cvzi/darkmodewallpaper)
[f-droid.org/.../darkmodewallpaper](https://f-droid.org/packages/com.github.cvzi.darkmodewallpaper)

**Comment by patzly** [comment]
@extropista Any information on how I should understand your request? Auto dark mode is one of the main features of Doodle, so I don't understand what you mean.

**Comment by extropista** [comment]
Hello, thanks for answering.

My suggestion came because it happened to me that when I changed the system dark mode (Android) the background image did not change automatically.
And now I realize that it does switch to dark mode, but only after locking the screen.

I am using a Xiaomi POCO X3 Pro, with Android 12 (MIUI 13.0.4)

**Comment by extropista** [comment]
I did the same process again, and the same thing happened, here I leave you an image of what I indicated.

![Screenshot_2022-07-12-19-01-24-687_app.lawnchair.jpg](https://user-images.githubusercontent.com/77421034/178612707-da7b0afe-af65-40ce-9510-86c6de4ba8fc.jpg)

**Comment by extropista** [comment]
With this image that I mark on the screenshot, the same thing that I described happened to me.


![IMG_20220712_193559.png](https://user-images.githubusercontent.com/77421034/178615953-810600d0-fd20-4de1-b766-b564d26ff0f5.png)

**Comment by Mimo13713k** [comment]
Good app

**Comment by patzly** [comment]
That's weird, I can say with evidence that all wallpapers should behave exactly the same, there should never be any different behavior. My only explanation for this would be the dark mode algorithm of your device. Also I think it's not a negative thing if dark mode is only applied after the screen turns off, the user should not see the change.
I will close this issue because I don't see a drastic bug in this behavior (but nevertheless maybe it improves for you with the next update which comes very soon). Please feel free to openthe issue again if you think it still doesn't behave as expected.
