### ISSUE TITLE
Option to generate static wallpaper instead of live

### ISSUE THREAD

**Issue by Dafelleant** [patzly/doodle-android#70]
An option to generate static wallpaper based on settings you choose as well as ability to use randomized one.

**Comment by patzly** [comment]
Why exactly do you want that? The main reason why this app exists are the parallax/zoom/tilt effects.
Also you could turn off parallax/zoom to make it static.

**Comment by Dafelleant** [comment]
> Why exactly do you want that? The main reason why this app exists are the parallax/zoom/tilt effects. Also you could turn off parallax/zoom to make it static.

Mostly for battery/performance saving purpose.

**Comment by patzly** [comment]
Thanks for your answer. I think Doodle is not the right place for this as it's all about moving shapes. Maybe you can try out my other (unreleased) app [Pallax](https://github.com/patzly/pallax-android), there you can turn static wallpapers into an auto dark mode parallax live wallpaper. For that you would have to download the static wallpapers from the web, they are all online available when you search for "Pixel 6 leaked wallpapers" and "Chrome OS wallpapers Kovecses".
Or you can keep Doodle and turn off parallax/zoom effects in settings. I have also implemented an option to turn off parallax and/or zoom and/or tilt effects automatically as soon as battery saver is turned on.
The implementation of all the features for static wallpapers in Doodle would be many hours of work, because static wallpapers are a completely different thing than live wallpapers regarding development and internal structures. As an example, auto dark mode is managed automatically by the live wallpaper service which is running always in background, it can keep dark mode synced with the system the whole time. If this would not be managed by a running wallpaper service (as it should be for static wallpapers), then this work has to be done by completely new background tasks/timers/callbacks, which would blow up the app unnecessarily as it is intended for live wallpapers.
