### ISSUE TITLE
Add sights from the sun live wallpaper

### ISSUE THREAD

**Issue by Seandylan123** [patzly/doodle-android#75]
So basically i'm tired of seeing those boring other wallpapers from doodle wallpapers adding sights from the sun live wallpaper would be really wonderful because i'm a fan of the solar system and making customisation for the speed and planets would be appreciating i want this to be added because it's missing a 2d live wallpaper the collection should be in the doodle collection

**Comment by Seandylan123** [comment]
I also forgot to mention i don't have a 64-bit device so if anyone using a 32bit phone that wanted this will be really appreciating for them

**Comment by patzly** [comment]
As the in-app info says, I won't add any 3D wallpaper to this app. Beside parallax and zoom effect, Doodle is simply unable to render 3D content like the wallpaper you want and is only meant to provide doodle-styled 2D shape wallpapers.
Also I think it has some reasons that the mentioned live wallpaper is only available for 64-bit devices, 3D engines have many restrictions regarding processors and shader rendering, that's all very complicated and would be an entire new big project. And if you find the existing wallpapers boring then maybe Doodle is not the right wallpaper app for you, because as I said, Doodle is meant to provide original Pixel doodle-styled wallpapers with improvements and customization options.

**Comment by Seandylan123** [comment]
> As the in-app info says, I won't add any 3D wallpaper to this app. Beside parallax and zoom effect, Doodle is simply unable to render 3D content like the wallpaper you want and is only meant to provide doodle-styled 2D shape wallpapers. Also I think it has some reasons that the mentioned live wallpaper is only available for 64-bit devices, 3D engines have many restrictions regarding processors and shader rendering, that's all very complicated and would be an entire new big project. And if you find the existing wallpapers boring then maybe Doodle is not the right wallpaper app for you, because as I said, Doodle is meant to provide original Pixel doodle-styled wallpapers with improvements and customization options.

I see i thought it was 2d because it look like that
