### ISSUE TITLE
Helvetica Blank

### ISSUE THREAD

**Issue by robsonsobral** [patzly/doodle-android#80]
Some artwork of [Helvetica Blank](https://helveticablanc.com/artwork.html) looks perfect for this app.

**Comment by patzly** [comment]
Thanks! They are very nice, but for me it would be nearly impossible to create the resources I need for Doodle. This includes extraction of all objects (the shapes are mostly not sharp and have many artefacts, not good for SVG) and creation of dark and light variants as each piece is a seperate artwork with its own colors and combinations.
And the last and most important point is copyright, I have no rights for these artworks and providing them in a wallpaper app would be not correct I think. For Google's own wallpapers it's a little different because the wallpapers are offered all over the internet and Google would never try to prevent that. Hope you understand that! :)

**Comment by robsonsobral** [comment]
Oh, I suggested because it's all [Creative Commons](https://helveticablanc.com/licensing.html). Also, the author could be contacted.

Thank you for your attention.

**Comment by patzly** [comment]
Oh I haven't seen this! That makes things better, but the main issue stays: it would be very very hard to extract each seperate object in the artworks (and to fill non-visible parts of a shape), the most important part for Doodle to be able to provide a parallax and zoom effect.
Also the licensing is a bit more complicated I think:

> If you remix, transform, or build upon my artwork, you must distribute your contributions under the same license.

would mean that I have to distribute Doodle under the Creative Commons license, but this is not the case.
